# Generated by Django 4.0.1 on 2022-01-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Product description')),
                ('category', models.CharField(choices=[('0', 'other'), ('1', 'smartphone'), ('2', 'computers')], default='0', max_length=30, verbose_name='Category')),
                ('remainder', models.PositiveIntegerField(verbose_name='Remainder')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
    ]
