# Generated by Django 4.0.1 on 2022-02-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='количество товара в корзине')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='webapp.product', verbose_name='Товар в корзине')),
            ],
            options={
                'verbose_name': 'product in cart',
                'verbose_name_plural': 'products in cart',
                'db_table': 'cart',
            },
        ),
    ]
